# Generated by Django 2.2.6 on 2019-10-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiprotseqalign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinsequence',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='sequence',
            field=models.TextField(),
        ),
    ]
