# Generated by Django 2.2.6 on 2019-10-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcelllocpred', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCellLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ProteinSequence',
        ),
    ]
